name: Deploy to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Pick the first site folder that actually exists
      - name: Locate site directory
        run: |
          for dir in public/combined comprehensive_site public dist; do
            if [ -d "$dir" ]; then
              echo "USING=$dir" >> $GITHUB_ENV
              echo "Publishing from: $dir"
              exit 0
            fi
          done
          echo "No site folder found (looked for: public/combined, comprehensive_site, public, dist)" >&2
          echo "Tip: ensure your index.html is in one of those folders on the main branch."
          exit 1

      - uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.USING }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
