name: Deploy to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use public/combined if your “combine” workflow created it; otherwise use public
      - name: Pick site folder
        run: |
          if [ -d public/combined ]; then
            echo "USING=public/combined" >> $GITHUB_ENV
          else
            echo "USING=public" >> $GITHUB_ENV
          fi
          echo "Publishing from: $USING"
          ls -la "$USING"

      - uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.USING }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
