name: Combine static HTML into public/combined

on:
  workflow_dispatch:
    inputs:
      source_glob:
        description: "Glob of files to copy"
        default: "comprehensive_site/**"
        required: true
      target_dir:
        description: "Target directory under public/"
        default: "combined"
        required: true

jobs:
  combine:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Copy files
        shell: bash
        run: |
          set -euo pipefail
          SRC="${{ github.event.inputs.source_glob }}"
          DEST="public/${{ github.event.inputs.target_dir }}"
          mkdir -p "$DEST"
          shopt -s globstar dotglob nullglob
          # rsync preserves structure and overwrites updated files
          rsync -a --delete --exclude ".git" $SRC "$DEST/"

      - name: Ensure index.html at target root (best effort)
        shell: bash
        run: |
          DEST="public/${{ github.event.inputs.target_dir }}"
          if [ ! -f "$DEST/index.html" ]; then
            found=$(find "$DEST" -maxdepth 3 -name index.html | head -n1 || true)
            if [ -n "$found" ]; then
              cp "$found" "$DEST/index.html"
            fi
          fi
          echo "Top-level index.html present?"; test -f "$DEST/index.html" && echo "yes" || echo "no"

      - name: Commit changes
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(combine): update public/${{ github.event.inputs.target_dir }}"
            git push
          fi
