name: Site Agent

on:
  workflow_dispatch:
    inputs:
      files:
        description: 'HTML file (or glob) to edit'
        required: true
        default: 'comprehensive_site/sites/**/*.html'
      ask:
        description: 'Instruction for the agent (English)'
        required: true
      plan_json:
        description: 'Optional JSON plan (leave empty for normal run)'
        required: false
      dry_run:
        description: 'Dry run (plan + diff only, no commit)'
        type: boolean
        required: false
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install agent deps (minimal)
        run: |
          mkdir -p tools/node_modules
          npm --prefix tools i --no-fund --no-audit --silent jsdom prettier fs-extra fast-glob

      - name: Capture inputs (preserve newlines safely)
        id: inputs
        shell: bash
        run: |
          {
            echo 'files<<__EOF__'
            echo "${{ inputs.files }}"
            echo '__EOF__'
            echo 'ask<<__EOF__'
            echo "${{ inputs.ask }}"
            echo '__EOF__'
            echo "dry_run=${{ inputs.dry_run }}"
          } >> "$GITHUB_OUTPUT"

          # Optional plan (multiline-safe)
          if [[ -n "${{ inputs.plan_json }}" ]]; then
            printf '%s\n' "${{ inputs.plan_json }}" > /tmp/plan.json
            echo "plan_file=/tmp/plan.json" >> "$GITHUB_OUTPUT"
          fi

      - name: Run site agent (apply instruction)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}   # optional; agent runs without if not needed
          OPENAI_PROJECT: ${{ secrets.OPENAI_PROJECT }}   # optional
        shell: bash
        run: |
          set -euo pipefail
          echo "Files: ${{ steps.inputs.outputs.files }}"
          echo "Ask:   ${{ steps.inputs.outputs.ask }}"
          PLAN_FLAG=""
          if [[ -n "${{ steps.inputs.outputs.plan_file }}" ]]; then
            PLAN_FLAG="--plan-json-file ${{ steps.inputs.outputs.plan_file }}"
          fi

          node tools/super-agent.mjs \
            --files "${{ steps.inputs.outputs.files }}" \
            --ask "${{ steps.inputs.outputs.ask }}" \
            ${PLAN_FLAG} \
            $([[ "${{ steps.inputs.outputs.dry_run }}" == "true" ]] && echo "--dry" || true)

      - name: Create Pull Request
        if: ${{ steps.inputs.outputs.dry_run != 'true' }}
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "agent/auto-${{ github.run_id }}"
          title: "Agent: site edit"
          body: "Requested by ${{ github.actor }}."
          commit-message: "Agent: site edit"
