name: Site Agent

on:
  workflow_dispatch:
    inputs:
      files:
        description: "HTML file (or glob) to edit"
        required: true
        default: "comprehensive_site/sites/**/*.html"
      ask:
        description: "Instruction for the agent (English)"
        required: true
      dry_run:
        description: "Dry run (plan + diff only, no commit)"
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install agent deps (minimal)
        run: |
          mkdir -p tools/node_modules
          npm --prefix tools i --no-fund --no-audit --no-save jsdom prettier fs-extra fast-glob

      - name: Run site agent (apply instruction)
        id: apply
        shell: bash
        run: |
          set -euo pipefail
          FILES="${{ inputs.files }}"
          ASK="${{ inputs.ask }}"
          DRY="${{ inputs.dry_run }}"
          echo "Files: $FILES"
          echo "Ask:   $ASK"
          node tools/super-agent.mjs \
            --files "$FILES" \
            --ask "$ASK" \
            $([ "$DRY" = "true" ] && echo "--dry" || true)

      - name: Create Pull Request
        if: inputs.dry_run == 'false'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "agent/auto-${{ github.run_id }}"
          title: "Agent: site edit"
          commit-message: "Agent: site edit"
          body: "Requested by ${{ github.actor }}."
